name: CI/CD Pipeline
on:
  push:
    branches: master
env:
  IMAGE_NAME: flask-app
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y conntrack curl wget apt-transport-https

          # Get latest kubectl version
          KUBECTL_VERSION=$(curl -s https://dl.k8s.io/release/stable.txt)

          # Download kubectl
          curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"

          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

            # Install Minikube
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          sudo minikube start --driver=docker
          minikube status
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml --validate=false
          kubectl apply -f service.yaml
